#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE order_db OWNER $POSTGRES_USER;
    CREATE DATABASE staff_db OWNER $POSTGRES_USER;
    CREATE DATABASE manager_db OWNER $POSTGRES_USER;
    CREATE DATABASE catalog_db OWNER $POSTGRES_USER;
    CREATE DATABASE pay_db OWNER $POSTGRES_USER;
    CREATE DATABASE ship_db OWNER $POSTGRES_USER;
    CREATE DATABASE comment_db OWNER $POSTGRES_USER;
    CREATE DATABASE recommender_db OWNER $POSTGRES_USER;
EOSQL
