services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore_mysql
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/init-customer-db.sql:/docker-entrypoint-initdb.d/init-customer-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bookstore_postgres
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_user -d bookstore_postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  customer-service:
    build: ./customer-service
    ports:
      - "8001:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./customer-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=customer_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=mysql-db
      - DB_PORT=3306
    depends_on:
      mysql-db:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    ports:
      - "8012:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./auth-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=auth_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - JWT_SECRET=bookstore-jwt-secret
      - JWT_ISSUER=bookstore-auth-service
      - JWT_AUDIENCE=bookstore-clients
    depends_on:
      postgres-db:
        condition: service_healthy

  book-service:
    build: ./book-service
    ports:
      - "8002:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./book-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=bookstore_mysql
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=mysql-db
      - DB_PORT=3306
    depends_on:
      mysql-db:
        condition: service_healthy

  clothe-service:
    build: ./clothe-service
    ports:
      - "8013:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./clothe-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=clothe_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  cart-service:
    build: ./cart-service
    ports:
      - "8003:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./cart-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=bookstore_postgres
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  order-service:
    build: ./order-service
    ports:
      - "8004:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./order-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=order_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  staff-service:
    build: ./staff-service
    ports:
      - "8005:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./staff-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=staff_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  manager-service:
    build: ./manager-service
    ports:
      - "8006:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./manager-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=manager_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  catalog-service:
    build: ./catalog-service
    ports:
      - "8007:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./catalog-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=catalog_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  pay-service:
    build: ./pay-service
    ports:
      - "8008:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./pay-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=pay_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  ship-service:
    build: ./ship-service
    ports:
      - "8009:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ship-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=ship_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  comment-rate-service:
    build: ./comment-rate-service
    ports:
      - "8010:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./comment-rate-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=comment_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy

  recommender-ai-service:
    build: ./recommender-ai-service
    ports:
      - "8011:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./recommender-ai-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=recommender_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - BOOK_SERVICE_URL=http://book-service:8000
      - ORDER_SERVICE_URL=http://order-service:8000
      - COMMENT_RATE_SERVICE_URL=http://comment-rate-service:8000
    depends_on:
      postgres-db:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api-gateway:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=bookstore_postgres
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8000
      - JWT_ISSUER=bookstore-auth-service
      - JWT_AUDIENCE=bookstore-clients
    depends_on:
      postgres-db:
        condition: service_healthy
      auth-service:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: bookstore_user
      PMA_PASSWORD: bookstore_pass
    depends_on:
      mysql-db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      postgres-db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  cart-worker:
    build: ./cart-service
    command: python app/consumer.py
    volumes:
      - ./cart-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=bookstore_postgres
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  pay-worker:
    build: ./pay-service
    command: python app/consumer.py
    volumes:
      - ./pay-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=pay_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - FORCE_PAYMENT_FAIL=false
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  ship-worker:
    build: ./ship-service
    command: python app/consumer.py
    volumes:
      - ./ship-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=ship_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - FORCE_SHIPPING_FAIL=false
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  order-worker:
    build: ./order-service
    command: python app/consumer.py
    volumes:
      - ./order-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=order_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

volumes:
  mysql_data:
  postgres_data:
