from django.urls import path
from .views import (
    home, book_list, customer_list, view_cart,
    admin_order_list, admin_order_detail,
    admin_staff_list, admin_manager_list, admin_catalog_list,
    admin_payment_list, admin_shipment_list, admin_review_list,
    store_home, store_login, store_register, store_logout,
    store_profile,
    store_cart, store_add_to_cart, store_remove_from_cart,
    store_book_detail, store_checkout,
    store_orders, store_order_detail, store_cancel_order,
    store_add_review,
    store_payment_simulate, store_confirm_receipt,
    api_secure_echo,
    admin_clothe_list, store_clothes, store_clothe_detail,
)

urlpatterns = [
    # Admin
    path('', home, name='home'),
    path('books/', book_list, name='book_list'),
    path('clothes/', admin_clothe_list, name='admin_clothe_list'),
    path('customers/', customer_list, name='customer_list'),
    path('cart/<int:customer_id>/', view_cart, name='view_cart'),
    path('orders/', admin_order_list, name='admin_order_list'),
    path('orders/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('staff/', admin_staff_list, name='admin_staff_list'),
    path('managers/', admin_manager_list, name='admin_manager_list'),
    path('catalog/', admin_catalog_list, name='admin_catalog_list'),
    path('payments/', admin_payment_list, name='admin_payment_list'),
    path('shipments/', admin_shipment_list, name='admin_shipment_list'),
    path('reviews/', admin_review_list, name='admin_review_list'),
    # Storefront
    path('store/', store_home, name='store_home'),
    path('store/clothes/', store_clothes, name='store_clothes'),
    path('store/clothes/<int:clothe_id>/', store_clothe_detail, name='store_clothe_detail'),
    path('store/login/', store_login, name='store_login'),
    path('store/register/', store_register, name='store_register'),
    path('store/logout/', store_logout, name='store_logout'),
    path('store/profile/', store_profile, name='store_profile'),
    path('store/cart/', store_cart, name='store_cart'),
    path('store/add-to-cart/', store_add_to_cart, name='store_add_to_cart'),
    path('store/remove-from-cart/<int:book_id>/', store_remove_from_cart, name='store_remove_from_cart'),
    path('store/book/<int:book_id>/', store_book_detail, name='store_book_detail'),
    path('store/checkout/', store_checkout, name='store_checkout'),
    path('store/orders/', store_orders, name='store_orders'),
    path('store/orders/<int:order_id>/', store_order_detail, name='store_order_detail'),
    path('store/orders/<int:order_id>/cancel/', store_cancel_order, name='store_cancel_order'),
    path('store/review/<int:book_id>/', store_add_review, name='store_add_review'),
    path('store/orders/<int:order_id>/pay/', store_payment_simulate, name='store_payment_simulate'),
    path('store/orders/<int:order_id>/confirm/', store_confirm_receipt, name='store_confirm_receipt'),
    path('api/secure-echo/', api_secure_echo, name='api_secure_echo'),
]
