# Generated by Django 5.2.12 on 2026-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('carrier', models.CharField(choices=[('ghn', 'Giao Hang Nhanh'), ('ghtk', 'Giao Hang Tiet Kiem'), ('viettel_post', 'Viettel Post'), ('jt_express', 'J&T Express')], default='ghn', max_length=30)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='preparing', max_length=20)),
                ('shipping_address', models.TextField()),
                ('estimated_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
